export const CULTURAL_CATEGORY = [
  'historic_ensemble',
  'museums_galleries',
  'monument',
  'memorial',
  'castle',
  'religious_heritage',
  'cultural_venues',
  'public_art',
  'industrial_heritage',
  'archaeological_sites',
  'heritage_buildings',
  'gardens_parks',
  'other',
];
